# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

# useDotenv: true
configValidationMode: off

service: bot-finansial

# Remember to install project dependencies to register the provider plugin.
# $ npm install
provider:
  name: openwhisk

functions:
#twitter
  postTweet:
    handler: src/handler/tweet.postTweet
    name: 'bot-finansial/postTweet'
    memory: 128
#emas
  scrapEmas:
    handler: src/handler/emas.scrapEmas
    name: 'bot-finansial/scrapEmas'
    memory: 128
  adapterEmas:
    handler: src/handler/emas.adapterEmas
    name: 'bot-finansial/adapterEmas'
    memory: 128
  sequenceEmas:
    name: 'bot-finansial/sequenceEmas'
    sequence:
      - 'scrapEmas'
      - 'adapterEmas'
      - 'postTweet'
  sequnceEmasDev:
    name: 'bot-finansial/sequenceEmasDev'
    sequence:
      - 'scrapEmas'
      - 'adapterEmas'
#crypto
  scrapCrypto:
    handler: src/handler/crypto.scrapCrypto
    name: 'bot-finansial/scrapCrypto'
    memory: 128
  adapterBitcoin:
    handler: src/handler/crypto.adapterBitcoin
    name: 'bot-finansial/adapterBitcoin'
    memory: 128
  sequenceBitcoin:
    name: 'bot-finansial/sequenceBitcoin'
    sequence:
      - 'scrapCrypto'
      - 'adapterBitcoin'
      - 'postTweet'
  sequenceBitcoinDev:
    name: 'bot-finansial/sequenceBitcoinDev'
    sequence:
      - 'scrapCrypto'
      - 'adapterBitcoin'
#idx
  scrapIdx:
    handler: src/handler/idx.scrapIdx
    name: 'bot-finansial/scrapIdx'
    memory: 128
  adapterIdx:
    handler: src/handler/idx.adapterIdx
    name: 'bot-finansial/adapterIdx'
    memory: 128
  sequenceIdx:
    name: 'bot-finansial/sequenceIdx'
    sequence:
      - 'scrapIdx'
      - 'adapterIdx'
      - 'postTweet'
  sequenceIdxDev:
    name: 'bot-finansial/sequenceIdxDev'
    sequence:
      - 'scrapIdx'
      - 'adapterIdx'
#forex
  scrapForex:
    handler: src/handler/forex.scrapForex
    name: 'bot-finansial/scrapForex'
    memory: 128
  adapterForex:
    handler: src/handler/forex.adapterForex
    name: 'bot-finansial/adapterForex'
    memory: 128
  sequenceForex:
    name: 'bot-finansial/sequenceForex'
    sequence:
      - 'scrapForex'
      - 'adapterForex'
      - 'postTweet'
  sequnceForexDev:
    name: 'bot-finansial/sequenceForexDev'
    sequence:
      - 'scrapForex'
      - 'adapterForex'
# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk

resources:
  apigw:
    name: 'bot-finansial'
    basepath: /serverless
    cors: true